platform :ios, '14.6'
target 'Gem Identifier' do
  use_frameworks!
  
 pod 'lottie-ios' 
 pod 'SDWebImage'
 pod 'AppsFlyerFramework' 
 pod 'YandexMobileMetrica'
 pod 'FBAudienceNetwork'
 pod 'Moya', '~> 15.0'
 pod 'UserAcquisition', :git => "https://github.com/inapps-io/UserAcquisition.git"
 pod 'KeychainSwift'
 
 pod 'Google-Mobile-Ads-SDK'
 pod 'GoogleMobileAdsMediationAdColony'
 pod 'GoogleMobileAdsMediationAppLovin'
 pod 'GoogleMobileAdsMediationIronSource'
 pod 'GoogleMobileAdsMediationVungle'
 pod 'GoogleMobileAdsMediationFacebook'
 pod 'GoogleMobileAdsMediationMintegral'
 pod 'GoogleMobileAdsMediationPangle'
 pod 'GoogleMobileAdsMediationUnity'

end


post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
